apiVersion: platform.awx.im/v1alpha1
kind: ClusterNodeNet
metadata:
  name: hackathon-demo
  namespace: default
  labels:
    purpose: hackathon
  annotations:
    crossplane.io/external-name: hackathon-demo
spec:
  compositionRevisionSelector:
    matchLabels:
      channel: demo
  id: awx-hack
  parameters:
    cluster: hackaton-cluster
    network: hackathon-net
    subnetwork: hackathon-subnet
  writeConnectionSecretToRef:
    name: hackaton-cluster-conn
